#!/usr/bin/env bash
# Build the verified Omniverse CPU environment.
#
# Two venvs on purpose: usd-exchange vendors its own OpenUSD under the
# pxrInternal_v0_25_5 namespace, and simready-validate depends on usd-core.
# Installing both into one venv loads two copies of the same C++ symbols and
# crashes. See docs/02-verified-findings.md §1.
#
#   .venv-ov        usd-exchange + converters + ovphysx/ovstage/ovrtx/newton
#   .venv-simready  simready-validate + usd-core + omniverse-asset-validator
#
# No GPU required. Verified on Linux x86_64 / Python 3.11.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OV_VENV="${OV_VENV:-$ROOT/.venv-ov}"
SR_VENV="${SR_VENV:-$ROOT/.venv-simready}"
UPSTREAM_ROOT="${PHYSICAL_AI_SKILL_HUB_UPSTREAM_ROOT:-$HOME/.physical-ai-skill-hub/upstreams}"

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# ---------------------------------------------------------------- system libs
say "System libraries"
# libOpenGL is needed by ovstage's Omniverse USD resolver plugin even headless.
# Without it, omniverse:// (Nucleus) URLs silently fail to resolve.
if ! ldconfig -p 2>/dev/null | grep -q libOpenGL; then
  if command -v apt-get >/dev/null 2>&1; then
    ${SUDO:-$([ "$(id -u)" -eq 0 ] || echo sudo)} apt-get install -y -qq \
      libopengl0 libglx0 libgl1 2>&1 | tail -1 || \
      echo "  WARN: could not install libOpenGL; Nucleus URLs will not resolve"
  else
    echo "  WARN: no apt-get; install libOpenGL/libGL manually"
  fi
else
  echo "  libOpenGL present"
fi

# ------------------------------------------------------------------- ov venv
say "Omniverse venv  ->  $OV_VENV"
[ -d "$OV_VENV" ] || python3 -m venv "$OV_VENV"
"$OV_VENV/bin/pip" install -q --upgrade pip
"$OV_VENV/bin/pip" install -q -r "$ROOT/scripts/requirements-ov.txt"

if "$OV_VENV/bin/pip" show usd-core >/dev/null 2>&1; then
  echo "  ERROR: usd-core is installed in the Omniverse venv."
  echo "         It conflicts with usd-exchange's vendored OpenUSD."
  echo "         Fix: rm -rf $OV_VENV && $0"
  exit 1
fi

"$OV_VENV/bin/python" - <<'PY'
import usdex.core
from pxr import Usd, UsdGeom, UsdPhysics
print("  usd-exchange  :", usdex.core.version())
for m in ("ovstage", "ovphysx", "ovrtx", "ovstream", "ovstorage", "newton", "warp"):
    try:
        mod = __import__(m)
        print("  %-13s: %s" % (m, getattr(mod, "__version__", "ok")))
    except Exception as e:
        print("  %-13s: UNAVAILABLE (%s)" % (m, type(e).__name__))
PY

# -------------------------------------------------------------- simready venv
say "SimReady venv  ->  $SR_VENV"
[ -d "$SR_VENV" ] || python3 -m venv "$SR_VENV"
"$SR_VENV/bin/pip" install -q --upgrade pip
"$SR_VENV/bin/pip" install -q -r "$ROOT/scripts/requirements-simready.txt"
echo "  simready-validate: $("$SR_VENV/bin/pip" show simready-validate | awk '/^Version/{print $2}')"

# ------------------------------------------------------- SimReady Foundation
say "SimReady Foundation specs  ->  $UPSTREAM_ROOT/simready-foundation"
mkdir -p "$UPSTREAM_ROOT"
if [ -d "$UPSTREAM_ROOT/simready-foundation/.git" ]; then
  echo "  already present"
else
  git clone --depth 1 -b main \
    https://github.com/NVIDIA/simready-foundation.git \
    "$UPSTREAM_ROOT/simready-foundation" 2>&1 | tail -1
fi

SPECS="$UPSTREAM_ROOT/simready-foundation/nv_core/sr_specs/docs"
for d in capabilities features profiles; do
  [ -d "$SPECS/$d" ] || { echo "  ERROR: missing $SPECS/$d"; exit 1; }
done
echo "  features: $(ls "$SPECS/features" | wc -l)   capabilities: $(ls "$SPECS/capabilities" | wc -l)"

cat > "$ROOT/.env.ov" <<EOF
# generated by scripts/bootstrap_env.sh
export OV_VENV="$OV_VENV"
export SR_VENV="$SR_VENV"
export SIMREADY_FOUNDATION_ROOT="$UPSTREAM_ROOT/simready-foundation"
export SIMREADY_FOUNDATION_SPEC_ROOT="$SPECS"
export PHYSICAL_AI_SKILL_HUB_UPSTREAM_ROOT="$UPSTREAM_ROOT"
EOF

say "Ready"
echo "  source .env.ov"
echo "  ./scripts/run_pipeline.sh examples/urdf/arm2.urdf"
